title: Mohamad
  Mohamadi # your name (or website title) here
logo: "/images/103618.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  My experience as a process analyst and my education provided me with a strong foundation in the analytical aspects of data engineering.
  <br><br>
  I am currently pursuing additional training and certifications to enhance my knowledge of programming languages, data modeling, and data warehousing. 
  <br><br>
  <a href="https://www.linkedin.com/in/m-moamadi/">View My LinkedIn Profile</a> 
# theme: jekyll-theme-minimal
google_analytics: G-VVP2WBY2SB # your Google Analytics tracking ID here
